### ISSUE TITLE
Add support for conditions like :if :unless etc

### ISSUE THREAD

**Issue by haseebeqx** [bigbinary/acts_in_sequence#5]
In some cases we might need to set custom value instead of the value from sequence.
For example if we set `display_order` of a field as the last one by default or directly use the value if certain value is provided .
it would be great if it is possible to add a condition like 
```ruby
acts_in_sequence column_name: :display_order, if: :valid_display_order_provided?
```

**Comment by sandip-mane** [comment]
I think the gem can skip adding the `sequence`/`display_order` when it is already provided.

**Comment by haseebeqx** [comment]
How to do that?

**Comment by sandip-mane** [comment]
Currently it's not supported by the gem, I will add a PR.

**Comment by sandip-mane** [comment]
You can update the gem and it should work.

**Comment by haseebeqx** [comment]
Thanks @sandip-mane
